const {
    REACT_APP_WHOS_API,REACT_APP_LOGIN_ROUTE,REACT_APP_REGISTER_ROUTE,REACT_APP_QUES_ROUTE,REACT_APP_IMG_ROUTE,REACT_APP_STATS_ROUTE,REACT_APP_UPDATE_ROUTE
} = process.env;

export {
    REACT_APP_WHOS_API, 
    REACT_APP_LOGIN_ROUTE,
    REACT_APP_REGISTER_ROUTE,
    REACT_APP_QUES_ROUTE,
    REACT_APP_IMG_ROUTE,
    REACT_APP_STATS_ROUTE,
    REACT_APP_UPDATE_ROUTE
}