const {
    REACT_APP_WHOS_API,
    REACT_APP_LOGIN_ROUTE,
    REACT_APP_REGISTER_ROUTE,
    REACT_APP_QUES_ROUTE,
    REACT_APP_IMG_ROUTE,
    REACT_APP_STATS_ROUTE,
    REACT_APP_UPDATE_ROUTE,
    REACT_APP_GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,
    REACT_APP_GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
    REACT_APP_GOOGLE_LOGIN_PATH: GOOGLE_LOGIN_PATH,
} = process.env

export {
    REACT_APP_WHOS_API, 
    REACT_APP_LOGIN_ROUTE,
    REACT_APP_REGISTER_ROUTE,
    REACT_APP_QUES_ROUTE,
    REACT_APP_IMG_ROUTE,
    REACT_APP_STATS_ROUTE,
    REACT_APP_UPDATE_ROUTE,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CLIENT_ID,
    GOOGLE_LOGIN_PATH,
}